language: scala

jdk:
- oraclejdk8

script: sbt "; project geojson-proto; set protobufProtoc := \"$HOME/protobuf/bin/protoc\"; project timeshape; test"

sudo: false

cache:
  directories:
    - "$HOME/protobuf"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

before_cache:
  - find $HOME/.ivy2/cache/net.iakovlev -depth -name "*timeshape" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

before_install:
  - bash .ci/install_protoc.sh